### ISSUE TITLE
Task Scheduled With Excessive Delay 

### ISSUE THREAD

**Issue by NZAbklepp** [anskarl/LoMRF#12]
When running through the "Quick Start" guide with the appropriately formatted knowledge base and evidence files, a task is scheduled which exceeds the maximum allowable delay throwing an unchecked exception. The full stack trace is below.

Exception in thread "main" java.lang.IllegalArgumentException: Task scheduled with [214748363] seconds delay, which is too far in future, maximum delay is [21474835] seconds
	at akka.actor.LightArrayRevolverScheduler.checkMaxDelay(LightArrayRevolverScheduler.scala:182)
	at akka.actor.LightArrayRevolverScheduler.akka$actor$LightArrayRevolverScheduler$$schedule(LightArrayRevolverScheduler.scala:168)
	at akka.actor.LightArrayRevolverScheduler.scheduleOnce(LightArrayRevolverScheduler.scala:134)
	at akka.actor.Scheduler.scheduleOnce(Scheduler.scala:205)
	at akka.actor.Scheduler.scheduleOnce$(Scheduler.scala:202)
	at akka.actor.LightArrayRevolverScheduler.scheduleOnce(LightArrayRevolverScheduler.scala:37)
	at akka.pattern.PromiseActorRef$.apply(AskSupport.scala:643)
	at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:335)
	at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:322)
	at lomrf.mln.grounding.MRFBuilder.buildNetwork(MRFBuilder.scala:108)
	at lomrf.app.InferenceCLI$.delayedEndpoint$lomrf$app$InferenceCLI$1(InferenceCLI.scala:358)
	at lomrf.app.InferenceCLI$delayedInit$body.apply(InferenceCLI.scala:38)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at lomrf.app.InferenceCLI$.main(InferenceCLI.scala:38)
	at lomrf.app.LoMRF$.$anonfun$new$1(LoMRF.scala:32)
	at lomrf.app.LoMRF$.$anonfun$new$1$adapted(LoMRF.scala:32)
	at lomrf.util.opt.MasterOptionParser.parse(MasterOptionParser.scala:49)
	at lomrf.util.opt.MasterOptionParser.parse$(MasterOptionParser.scala:37)
	at lomrf.app.LoMRF$.parse(LoMRF.scala:25)
	at lomrf.app.LoMRF$.delayedEndpoint$lomrf$app$LoMRF$1(LoMRF.scala:46)
	at lomrf.app.LoMRF$delayedInit$body.apply(LoMRF.scala:25)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at lomrf.app.LoMRF$.main(LoMRF.scala:25)
	at lomrf.app.LoMRF.main(LoMRF.scala)

**Comment by vagmcs** [comment]
Hello @NZAbklepp,

I was able to reproduce the problem in the master branch. However, the develop branch seems to work properly. Can you please clone and run the develop branch? In the meantime we are investigating the issue.

**Comment by NZAbklepp** [comment]
Thanks for looking into it, @vagmcs. I've cloned, built and installed the develop branch, but I'm still having the same issue. I have the executables built from the develop branch added to my class path and the executables built from the master branch on a separate path. Executing either gives the same error :(

**Comment by vagmcs** [comment]
Hello @NZAbklepp,

What version of Java and Scala do you use for running LoMRF?

**Comment by NZAbklepp** [comment]
@vagmcs, I am using java version 1.8.0_111 and scala version 2.12.6

**Comment by anskarl** [comment]
Hi @NZAbklepp I think that it should be fine now

**Comment by NZAbklepp** [comment]
Thanks so much @anskarl that definitely did the trick! Everything seems to be running fine now.
