### ISSUE TITLE
java.io.IOException: Stream not marked

### ISSUE THREAD

**Issue by NZAbklepp** [anskarl/LoMRF#14]
I have a theory.mln file that looks something like this: 

    // Domain
    Pred = {0 , ... , 2544859}
    OverUnder = {0 , ... , 267090}
    Step={1 , ... , 12}

    // Predicate Schema
    SundayPred(Pred) 
    MondayPred(Pred)
    TuesdayPred(Pred)  
    WednesdayPred(Pred)
    ThursdayPred(Pred)
    FridayPred(Pred)
    SaturdayPred(Pred)
    1Pred(Pred)
    2Pred(Pred)
    3Pred(Pred)
    ...
    1PeriodPred(Pred)
    2PeriodPred(Pred)
    ...
    OverPred(Pred,OverUnder)
    UnderPred(Pred,OverUnder)
    BestApe(Pred,Step)
    RushPred(Pred)
    HolidayPred(Pred)

    // Hard Constraint Rules
    // No prediction can be over or under by more than one percentage
    OverPred(x,y) ^ OverPred(x,z) => y=z .
    UnderPred(x,y) ^ UnderPred(x,z) => y=z .

    // Weighted Rules 
    SundayPred(x) ^ 1Pred(x) ^ y=1 => BestApe(x,y)
    SundayPred(x) ^ 1Pred(x) ^  HolidayPred(x) ^ y=1 => BestApe(x,y)
    SundayPred(x) ^ 1Pred(x) ^ RushPred(x) ^ y=1 => BestApe(x,y)
    SundayPred(x) ^ 1Pred(x) ^ y=1 => BestApe(x,y)
    SundayPred(x) ^ 1Pred(x) ^ y=2 => BestApe(x,y)
    ...

Using the following command: 

> lomrf wlearn -i theory.mln -o theory.mln -t Data/Evidence/Converted/evidence_400082.db -ne UnderPred/2 -ne OverPred/2 -ne BestApe/2

when attempting to learn weights for MLN I get the following error message and stack trace: 

    Version: 1.0.0-SNAPSHOT
    [INFO ] Parameters:
	(ne) Non-evidence predicate(s): UnderPred/2,OverPred/2,BestApe/2
	(addUnitClauses) Include unit clauses in the output MLN file: false
	(sigma) Parameter for strong convexity in CDA: 1.0
	(lambda) Regularization parameter for ADAGRAD: 0.01
	(eta) Learning rate parameter for ADAGRAD: 1.0
	(delta) Delta parameter for ADAGRAD: 1.0
	(C) Soft-margin regularization parameter: 1000.0
	(epsilon) Stopping criterion parameter: 0.001
	(lossScale) Scale the loss value by: 1.0
	(iterations) Number of iterations for learning: 1000
	(L1Regularization) Use L1 regularization instead of L2: false
	(printLearnedWeightsPerIteration) Print learned weights for each iteration: false
	(ilpSolver) ILP solver used for learning and map inference: LpSolve
	(algorithm) Algorithm used to perform learning: Max-Margin
	(lossAugmented) Perform loss augmented inference: false
	(nonMarginRescaling) Don't scale the margin by the loss: false
	(noNegWeights) Eliminate negative weights: false
	(noNegatedUnit) Eliminate negated ground unit clauses: false
    [WARN ] For MAX_MARGIN training, only GUROBI solver is supported. Switching to GUROBI.  
    [INFO ] --- Stage 0: Loading an MLN instance from data...
	Input MLN file: theory.mln
	Input training file(s): Data/Evidence/Converted/evidence_400082.db
        Exception in thread "main" java.io.IOException: Stream not marked

	at java.io.BufferedReader.reset(BufferedReader.java:512)
	at lomrf.mln.model.KB$.fromFile(KB.scala:220)
	at lomrf.mln.model.MLN$.forLearning(MLN.scala:377)
	at lomrf.app.WeightLearningCLI$.weightLearn(WeightLearningCLI.scala:254)
	at lomrf.app.WeightLearningCLI$.delayedEndpoint$lomrf$app$WeightLearningCLI$1(WeightLearningCLI.scala:315)
	at lomrf.app.WeightLearningCLI$delayedInit$body.apply(WeightLearningCLI.scala:37)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at lomrf.app.WeightLearningCLI$.main(WeightLearningCLI.scala:37)
	at lomrf.app.LoMRF$.$anonfun$new$2(LoMRF.scala:33)
	at lomrf.app.LoMRF$.$anonfun$new$2$adapted(LoMRF.scala:33)
	at lomrf.util.opt.MasterOptionParser.parse(MasterOptionParser.scala:49)
	at lomrf.util.opt.MasterOptionParser.parse$(MasterOptionParser.scala:37)
	at lomrf.app.LoMRF$.parse(LoMRF.scala:25)
	at lomrf.app.LoMRF$.delayedEndpoint$lomrf$app$LoMRF$1(LoMRF.scala:46)
	at lomrf.app.LoMRF$delayedInit$body.apply(LoMRF.scala:25)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at lomrf.app.LoMRF$.main(LoMRF.scala:25)
	at lomrf.app.LoMRF.main(LoMRF.scala)

**Comment by anskarl** [comment]
It looks like the `theory.mln` is not correct.

Domain types must be lower-cased:
```
// Domain
pred = {0 , ... , 2544859}
overUnder = {0 , ... , 267090}
step={1 , ... , 12}
```

The following predicates are invalid:
```
1Pred(Pred)
2Pred(Pred)
3Pred(Pred)
...
1PeriodPred(Pred)
2PeriodPred(Pred)
```

First of all predicates cannot start with a number and secondly the symbol `Pred` (domain type) should become `pred` (lower-cased). For example, consider to change `1Pred(Pred)` into `Pred1(pred)`.

Also consider to change rules like the following

```
SundayPred(x) ^ 1Pred(x) ^ y=1 => BestApe(x,y)
```

into the equivalent and much faster for grounding:

```
SundayPred(x) ^ Pred1(x) => BestApe(x,1)
```

For details regarding the syntax of a knowledge base see the documentation in https://github.com/anskarl/LoMRF/blob/develop/docs/1_1_knowledge_base.md

**Comment by NZAbklepp** [comment]
Thanks for that! I have fixed the syntax for the `theory.mln`. New `theory.mln` looks something like this: 

    // Domain
    pred = {0 , ... , 2544859}
    overUnder = {0 , ... , 267090}
    step={1 , ... , 12}

    // predicate Schema
    predSunday(pred)
    predMonday(pred)
    predTuesday(pred)
    predWednesday(pred)
    predThursday(pred)
    predFriday(pred)
    predSaturday(pred)
    pred1(pred)
    pred2(pred)
    ...
    period1pred(pred)
    period2pred(pred)
    ...
    overpred(pred,overUnder)
    underpred(pred,overUnder)
    bestApe(pred,step)
    rushpred(pred)
    holidaypred(pred)

    // Hard Constraint Rules
    // No prediction can be over or under by more than one percentage
    overpred(x,y) ^ overpred(x,z) => y=z .
    underpred(x,y) ^ underpred(x,z) => y=z .

    // Weighted Rules
    predSunday(x) ^ pred1(x) => bestApe(x,1) 
    predSunday(x) ^ pred1(x) ^ holidaypred(x) => bestApe(x,1)
    predSunday(x) ^ pred1(x) ^ rushpred(x) => bestApe(x,1)
    ...

However same issue still! Interestingly the `theory.mln` file is completely consumed after running the above command, leaving an empty file in its place.

**Comment by NZAbklepp** [comment]
I have fixed the theory.mln files as well as all of the training files. My theory.mln currently looks like the following: 

    // Domain
    pred = {0 , ... , 2544859}
    overUnder = {0 , ... , 267090}
    step={1 , ... , 12}

    // predicate Schema
    sundayPred(pred) 
    mondayPred(pred)
    tuesdayPred(pred)
    wednesdayPred(pred)
    thursdayPred(pred)
    fridayPred(pred)
    saturdayPred(pred)
    pred1(pred)
    pred2(pred)
    ...
    period1Pred(pred)
    period2Pred(pred)
    ...
    baselineHAPred(pred)
    baselineRWPred(pred)
    ...
    // Hard Constraint Rules
    // No prediction can be over or under by more than one percentage
    overPred(x,y) ^ overPred(x,z) => y=z .
    underPred(x,y) ^ underPred(x,z) => y=z .

    // Weighted Rules
    baselineHAPred(x) ^ sundayPred(x) ^ pred1(x) => bestApe(x,1)
    baselineHAPred(x) ^ sundayPred(x) ^ pred1(x) ^ holidayPred(x) => bestApe(x,1)
    baselineHAPred(x) ^ sundayPred(x) ^ pred1(x) ^ rushPred(x) => bestApe(x,1)
    ...

Still same error message. Interestingly this also consumes the entire theory.mln file and leaves an empty file in its place.

**Comment by NZAbklepp** [comment]
Thanks for the heads-up! 

I have fixed the theory.mln file and all training files. Currently the theory.mln looks something like this: 
```
// Domain
pred = {0 , ... , 2544859}
overUnder = {0 , ... , 267090}
step={1 , ... , 12}

// predicate Schema
SundayPred(pred)
MondayPred(pred)
TuesdayPred(pred)
WednesdayPred(pred)
ThursdayPred(pred)
FridayPred(pred)
SaturdayPred(pred)
Pred1(pred)
Pred2(pred)
...
Period1Pred(pred)
Period2Pred(pred)
...
RegPred(pred)
SarimaPred(pred)
OverPred(pred,overUnder)
UnderPred(pred,overUnder)
BestApe(pred,step)
RushPred(pred)
HolidayPred(pred)
...

// Hard Constraint Rules
// No prediction can be over or under by more than one percentage
OverPred(x,y) ^ OverPred(x,z) => y=z .
UnderPred(x,y) ^ UnderPred(x,z) => y=z .

// Weighted Rules
BaselineHAPred(x) ^ SundayPred(x) ^ Pred1(x) => BestApe(x,1)
BaselineHAPred(x) ^ SundayPred(x) ^ Pred1(x) ^ HolidayPred(x) => BestApe(x,1)
...
```
Same problem persists. Interestingly this problem also consumes all of the content of the theory.mln file and leaves an empty file in its place.

**Comment by vagmcs** [comment]
Hello @NZAbklepp,

Can you please attach the full mln and evidence files in order for us to reproduce the issue?

**Comment by anskarl** [comment]
Hi @NZAbklepp,

It would be helpful to give us a reproducible example with an MLN and a DB file, since we can only make guesses. It doesn't have to be the complete MLN and DB files, just the fraction of clauses and predicates that causes the issue. 

Another guess, I think that LoMRF parser may confused where the predicate schema defintion ends. Could you please try to add a quantifier in the first clause that appears in the MLN file.

For example `OverPred(x,y) ^ OverPred(x,z) => y=z.` should become `Forall x,y,z OverPred(x,y) ^ OverPred(x,z) => y=z.`.

**Comment by NZAbklepp** [comment]
apologies that this took a few days. Was out of town and unable to upload until now. 

I have uploaded the theory.mln file and one of the evidence files that I am trying to use. I have changed their extensions to .txt for github compatability purposes, though on my system they still have the .mln and .db extensions. 

I have added the universal quantifier to the first hard constrained rule with no success in alleviating the issue. Also, the output from the LoMRF command SEEMS to indicate that this is more of an issue with the evidence file than with the theory specs, as the crash occurs after recognizing the evidence file and not the theory file: 

```
[INFO ] --- Stage 0: Loading an MLN instance from data...
	Input MLN file: theory.mln
	Input training file(s): Data/Evidence/Converted/evidence_400867.db
Exception in thread "main" java.io.IOException: Stream not marked
```

Of course I don't know if that is the case, just something I'm observing.

Thanks for your help! 

[theory.txt](https://github.com/anskarl/LoMRF/files/3447580/theory.txt)
[evidence_400096.txt](https://github.com/anskarl/LoMRF/files/3447581/evidence_400096.txt)

**Comment by anskarl** [comment]
Oh I haven't noticed in the beginning, the issue is that you are setting the same MLN file name as input and as output. 

Just change `-o theory.mln` to some different file name, e.g., `-o theory.output.mln`. For example:

```
lomrf wlearn -i theory.mln -o theory.output.mln -t Data/Evidence/Converted/evidence_400082.db -ne UnderPred/2 -ne OverPred/2 -ne BestApe/2
```

We may need to add a simple check for that, in order to have some helpful error message.

**Comment by anskarl** [comment]
Please note that another issue that you are going to have is that the number of possible ground predicates is far greater than Int.MaxValue (2147483647) and you are going to see an error like the following:

```
[INFO ] --- Stage 3: Creating function mappings, and evidence database.
Exception in thread "main" java.lang.AssertionError: assertion failed: Atom identity function requires startID to be greater than zero and you gave: -2086228309
        at scala.Predef$.assert(Predef.scala:223)
        at lomrf.mln.model.AtomIdentityFunction$.apply(AtomIdentityFunction.scala:351)
        at lomrf.mln.model.PredicateSpace$.$anonfun$apply$3(PredicateSpace.scala:119)
        at lomrf.mln.model.PredicateSpace$.$anonfun$apply$3$adapted(PredicateSpace.scala:115)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:792)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:234)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:465)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:465)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:791)
        at lomrf.mln.model.PredicateSpace$.apply(PredicateSpace.scala:115)
        at lomrf.mln.model.EvidenceBuilder$.apply(EvidenceBuilder.scala:337)
        at lomrf.mln.model.Evidence$.fromFiles(Evidence.scala:196)
        at lomrf.mln.model.Evidence$.fromFiles(Evidence.scala:84)
        at lomrf.mln.model.MLN$.forLearning(MLN.scala:401)
        at lomrf.app.WeightLearningCLI$.weightLearn(WeightLearningCLI.scala:254)
        at lomrf.app.WeightLearningCLI$.delayedEndpoint$lomrf$app$WeightLearningCLI$1(WeightLearningCLI.scala:315)
        at lomrf.app.WeightLearningCLI$delayedInit$body.apply(WeightLearningCLI.scala:37)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at lomrf.app.WeightLearningCLI$.main(WeightLearningCLI.scala:37)
        at lomrf.app.LoMRF$.$anonfun$new$2(LoMRF.scala:33)
        at lomrf.app.LoMRF$.$anonfun$new$2$adapted(LoMRF.scala:33)
        at lomrf.util.opt.MasterOptionParser.parse(MasterOptionParser.scala:49)
        at lomrf.util.opt.MasterOptionParser.parse$(MasterOptionParser.scala:37)
        at lomrf.app.LoMRF$.parse(LoMRF.scala:25)
        at lomrf.app.LoMRF$.delayedEndpoint$lomrf$app$LoMRF$1(LoMRF.scala:46)
        at lomrf.app.LoMRF$delayedInit$body.apply(LoMRF.scala:25)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at lomrf.app.LoMRF$.main(LoMRF.scala:25)
        at lomrf.app.LoMRF.main(LoMRF.scala)
```

In the theory.mln file you have the following domain definition:
```
pred = {0 , ... , 2544859}
overUnder = {0 , ... , 267090}
step={1 , ... , 12}
```
and given the predicate definitions you have:
  
  * 126 x 2544860 = 320652360: ground predicates having single argument `pred`
  * 2 x 2544860 x 267091 = 1359418404520: ground predicates having arguments `pred` and `overUnder`
  * 1 x 2544860 x 12 = 30538320: ground predicates having arguments `pred` and `step`

That is total: 1359769595200 ground predicates, which is >> 2147483647.

I think that you need to reduce the domain size.

**Comment by NZAbklepp** [comment]
Excellent. Thanks for all of your help!
