### ISSUE TITLE
Error in sbt test

### ISSUE THREAD

**Issue by NZAbklepp** [anskarl/LoMRF#17]
The build and link seems to work fine, but the test fails. Here is the output: 

```
[develop] LoMRF: test
[info] Headers created for 36 files:
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/inference/ILPSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/inference/MCSATSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/inference/MaxWalkSATSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/structure/ModeParserSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/structure/hypergraph/HypergraphSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/structure/hypergraph/HPathSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/structure/hypergraph/PathTemplateSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/supervision/metric/StructureMetricSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/supervision/graphs/GraphConnectorSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/weight/MaxMarginSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/model/ConstantsDomainBuilderSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/model/KBBuilderSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/model/EvidenceBuilderSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/model/AtomIdentityFunctionSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/grounding/DependencyMapSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/mln/grounding/GroundingSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/AtomSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/TermSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/AtomSignatureSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/SimilaritySpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/ClauseSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/parser/EvidenceParserSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/parser/DomainParserSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/parser/KBParserSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/UnificationSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/compile/LogicFormatterSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/compile/NormalFormSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/TriStateSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/logic/SubsumptionSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/tests/TestData.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/tests/ECExampleDomain1.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/util/CartesianSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/util/LongDoubleSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/util/evaluation/MetricsSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/util/collection/mutable/TuplesDBSpecTest.scala
[info]   /home/administrator/LoMRF/src/test/scala/lomrf/util/collection/GlobalIndexPartitionedSpecTest.scala
[info] Formatting 37 Scala sources ProjectRef(uri("file:/home/administrator/LoMRF/"), "LoMRF")(test) ...
[warn] Scalariform parser error for /home/administrator/LoMRF/src/test/scala/lomrf/logic/compile/PredicateCompletionSpecTest.scala: illegal start of simple expression: Token(RPAREN,),1302,))
[info] Reformatted 36 Scala sources ProjectRef(uri("file:/home/administrator/LoMRF/"), "LoMRF")(test).
[info] Compiling 37 Scala sources to /home/administrator/LoMRF/target/scala-2.12/test-classes ...
[warn] /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/weight/MaxMarginSpecTest.scala:108:42: dead code following this construct
[warn]     val trueCounts: Array[Int] = learner invokePrivate countGroundings()
[warn]                                          ^
[warn] /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/weight/MaxMarginSpecTest.scala:140:13: dead code following this construct
[warn]     learner invokePrivate updateConstraintWeights()
[warn]             ^
[warn] /home/administrator/LoMRF/src/test/scala/lomrf/mln/learning/weight/MaxMarginSpecTest.scala:171:32: dead code following this construct
[warn]     val loss: Double = learner invokePrivate calculateError()
[warn]                                ^
[warn] three warnings found
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/administrator/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.8/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Unrecognized VM option 'UseFastAccessorMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[error] Could not accept connection from test agent: class java.net.SocketException: Socket closed
[error] java.net.SocketException: Socket closed
[error] 	at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
[error] 	at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458)
[error] 	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:551)
[error] 	at java.base/java.net.ServerSocket.accept(ServerSocket.java:519)
[error] 	at sbt.ForkTests$Acceptor$2$.run(ForkTests.scala:71)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[info] Run completed in 74 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
```
I have not yet been able to build the auxlib. Open issue pending on that repository.

**Comment by anskarl** [comment]
according to the error below:

```
Unrecognized VM option 'UseFastAccessorMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
``` 

I assume that you are using java 10 or greater. At the moment we haven't tested LoMRF to java version greater that 8. You can switch back to version 8, otherwise you may try to remove the JVM flag `UseFastAccessorMethods` from `project/LoMRFBuild.scala` file.
```
...
private lazy val JavaSettings: Seq[Setting[_]] = Seq(
    javacOptions ++= Seq("-source", "1.8", "-target", "1.8", "-Xlint:unchecked", "-Xlint:deprecation"),

    javaOptions ++= Seq(
      "-XX:+DoEscapeAnalysis",
      "-XX:+UseFastAccessorMethods",
      "-XX:+OptimizeStringConcat",
      "-Dlogback.configurationFile=src/main/resources/logback.xml")
  )
...
```

Recent versions of LoMRF does not depend on `auxlib`, therefore you don't have to build `auxlib`.

**Comment by anskarl** [comment]
@NZAbklepp I've made some changes in order to use LoMRF in recent java run-time environments, up to version 11. Please note that it is not yet thoroughly tested in Java 11.

**Comment by NZAbklepp** [comment]
Okay, great. Thanks for that. I switched to Java 8 and it seems to work fine. Haven't tried the Java 11 support changes yet.
