### ISSUE TITLE
Structure Learning Error

### ISSUE THREAD

**Issue by NZAbklepp** [anskarl/LoMRF#18]
I can't seem to run the structure learning algorithm with my setup.

I'm using an evidence file that looks something like this: 

```
eq(1500)=1500
fwy(400000)=101
dir(400000)=S
abs_pm(400000)=459.835
fwy(400001)=101
dir(400001)=N
abs_pm(400001)=387.897
...
Flow(402579,00:00:00,157,0)
Flow(402579,00:05:00,151,0)
Flow(402579,00:10:00,151,0)
Flow(402579,00:15:00,145,0)
...
CHP(23:45:00,4,E,29.731,0)
CHP(23:45:00,101,S,474.9,0)
CHP(23:45:00,80,E,3.2,0)
...
Eq(0,0)
Eq(1,1)
...
```
and an input theory.mln that looks like this: 

```
// Predicates
Flow(sid,time,flow,day)
CHP(time,fwy,dir,abs_pm,day)
Eq(flow,flow)
// Functions
fwy fwy(sid)
dir dir(sid)
abs_pm abs_pm(sid)
```

and the modes file is 

```
modeP(2,Flow(.,.,.,.))
modeP(2,CHP(.,.,.,.,.))
modeP(2,Eq(.,.))
modeF(2,fwy(.))
modeF(2,dir(.))
modeF(2,abs_pm(.))
```

and the command is 

```
lomrf slearn -i theory.mln -t Evidence/ -o learned.mln -m traffic.modes -ne CHP/5 -maxLength 12 -lambda 0.001 -threshold 2
```

Finally, the error I'm getting is:

```
assertion failed: KB should be created with the flag 'convertFunctions = true'
```

Here is the full output and stack trace: 

```
Version: 1.0.0-SNAPSHOT
[INFO ] Parameters:
	(ne) Non-evidence predicate(s): CHP/5
	(maxLength) Maximum length of literals for each clause produced: 12
	(allowFreeVariables) Allow clauses to have free variables: false
	(threshold) Evaluation threshold for each new clause produced: 2
	(theta) Tolerance threshold for discarding clauses having poor weights: 0.0
	(clauseType) Type of clauses to be produced: Both
	(ilpSolver) Solver used by ILP map inference: LpSolve
	(lossAugmented) Perform loss augmented inference: false
	(initialWeight) Initial weight value for discovered clauses: 0.01
	(lambda) Regularization parameter for AdaGrad: 0.001
	(eta) Learning rate parameter for AdaGrad: 1.0
	(delta) Delta parameter for AdaGrad: 1.0
	(noNegWeights) Eliminate negative weights: false
	(noNegatedUnit) Eliminate negated ground unit clauses: false
[INFO ] Modes Declarations: 
	AUXdir/2 -> mode(2,+,., Set())
	Flow/4 -> mode(2,.,.,.,., Set())
	AUXfwy/2 -> mode(2,+,., Set())
	AUXabs_pm/2 -> mode(2,+,., Set())
	CHP/5 -> mode(2,.,.,.,.,., Set())
[INFO ] Total formulas: 0
[INFO ] Step 1 / 355: Processing chunk Evidence/01_01_2017.db
Exception in thread "main" java.lang.AssertionError: assertion failed: KB should be created with the flag 'convertFunctions = true'
	at scala.Predef$.assert(Predef.scala:223)
	at lomrf.mln.learning.structure.TrainingEvidence$.fromFiles(TrainingEvidence.scala:152)
	at lomrf.app.StructureLearningCLI$.$anonfun$structLearn$14(StructureLearningCLI.scala:264)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at lomrf.app.StructureLearningCLI$.structLearn(StructureLearningCLI.scala:260)
	at lomrf.app.StructureLearningCLI$.delayedEndpoint$lomrf$app$StructureLearningCLI$1(StructureLearningCLI.scala:304)
	at lomrf.app.StructureLearningCLI$delayedInit$body.apply(StructureLearningCLI.scala:38)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at lomrf.app.StructureLearningCLI$.main(StructureLearningCLI.scala:38)
	at lomrf.app.LoMRF$.$anonfun$new$3(LoMRF.scala:34)
	at lomrf.app.LoMRF$.$anonfun$new$3$adapted(LoMRF.scala:34)
	at lomrf.util.opt.MasterOptionParser.parse(MasterOptionParser.scala:49)
	at lomrf.util.opt.MasterOptionParser.parse$(MasterOptionParser.scala:37)
	at lomrf.app.LoMRF$.parse(LoMRF.scala:25)
	at lomrf.app.LoMRF$.delayedEndpoint$lomrf$app$LoMRF$1(LoMRF.scala:46)
	at lomrf.app.LoMRF$delayedInit$body.apply(LoMRF.scala:25)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at lomrf.app.LoMRF$.main(LoMRF.scala:25)
	at lomrf.app.LoMRF.main(LoMRF.scala)
```

If I try to add the following rules to the theory.mln to make this: 

```
// Predicates
Flow(sid,time,flow,day)
CHP(time,fwy,dir,abs_pm,day)

// Functions
fwy fwy(sid)
dir dir(sid)
abs_pm abs_pm(sid)
flow eq(flow)

// Rules
Flow(x,y,u,z) ^	Flow(x,y,v,z) => eq(u,v)
```

I get the following error instead: 
```
Version: 1.0.0-SNAPSHOT
[INFO ] Parameters:
	(ne) Non-evidence predicate(s): CHP/5
	(maxLength) Maximum length of literals for each clause produced: 12
	(allowFreeVariables) Allow clauses to have free variables: false
	(threshold) Evaluation threshold for each new clause produced: 2
	(theta) Tolerance threshold for discarding clauses having poor weights: 0.0
	(clauseType) Type of clauses to be produced: Both
	(ilpSolver) Solver used by ILP map inference: LpSolve
	(lossAugmented) Perform loss augmented inference: false
	(initialWeight) Initial weight value for discovered clauses: 0.01
	(lambda) Regularization parameter for AdaGrad: 0.001
	(eta) Learning rate parameter for AdaGrad: 1.0
	(delta) Delta parameter for AdaGrad: 1.0
	(noNegWeights) Eliminate negative weights: false
	(noNegatedUnit) Eliminate negated ground unit clauses: false
[INFO ] Modes Declarations: 
	AUXdir/2 -> mode(2,+,., Set())
	Flow/4 -> mode(2,.,.,.,., Set())
	AUXfwy/2 -> mode(2,+,., Set())
	AUXabs_pm/2 -> mode(2,+,., Set())
	CHP/5 -> mode(2,.,.,.,.,., Set())
Exception in thread "main" java.io.IOException: Mark invalid
	at java.io.BufferedReader.reset(BufferedReader.java:512)
	at lomrf.mln.model.KB$.fromFile(KB.scala:220)
	at lomrf.app.StructureLearningCLI$.structLearn(StructureLearningCLI.scala:250)
	at lomrf.app.StructureLearningCLI$.delayedEndpoint$lomrf$app$StructureLearningCLI$1(StructureLearningCLI.scala:304)
	at lomrf.app.StructureLearningCLI$delayedInit$body.apply(StructureLearningCLI.scala:38)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at lomrf.app.StructureLearningCLI$.main(StructureLearningCLI.scala:38)
	at lomrf.app.LoMRF$.$anonfun$new$3(LoMRF.scala:34)
	at lomrf.app.LoMRF$.$anonfun$new$3$adapted(LoMRF.scala:34)
	at lomrf.util.opt.MasterOptionParser.parse(MasterOptionParser.scala:49)
	at lomrf.util.opt.MasterOptionParser.parse$(MasterOptionParser.scala:37)
	at lomrf.app.LoMRF$.parse(LoMRF.scala:25)
	at lomrf.app.LoMRF$.delayedEndpoint$lomrf$app$LoMRF$1(LoMRF.scala:46)
	at lomrf.app.LoMRF$delayedInit$body.apply(LoMRF.scala:25)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at lomrf.app.LoMRF$.main(LoMRF.scala:25)
	at lomrf.app.LoMRF.main(LoMRF.scala)
```

**Comment by vagmcs** [comment]
Hi @NZAbklepp,

I found the issue and have prepared a fix for it. It will be merged into the develop branch today or tomorrow I believe. Apart from that let me point out some problems with the provided evidence file:

1. Function evidence should be given as `101=fwy(400000)` not `fwy(400000)=101`. See [here](https://github.com/anskarl/LoMRF/blob/develop/docs/1_2_evidence.md) for more details.

2. Every function/predicate should have be declared into the .mln file as well as the .modes file. For instance you have given evidence for function `eq(1500)=1500` but it does not exist in the mln and modes files.

I will let you know when the fix is available.

**Comment by vagmcs** [comment]
Hi @NZAbklepp,

The fix is available in the develop branch.

**Comment by NZAbklepp** [comment]
Thanks so much! Works like a charm.
