### ISSUE TITLE
Exception when running CMD infer 

### ISSUE THREAD

**Issue by a-little-srdjan** [anskarl/LoMRF#19]
Environment:
Scala 2.11.12
openjdk version "11.0.6"
LoMRF 1.0.0-snapshot from current develop branch

Description:
When running: ```lomrf infer -i uniform.mln -q Heads/1 -r output``` or any other infer example from LoMRF-data/Examples/Inference I get the following exception:

```
Exception in thread "main" java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap')                 

at lomrf.app.InferenceCLI$.delayedEndpoint$lomrf$app$InferenceCLI$1(InferenceCLI.scala:327)                                                                                                                            
at lomrf.app.InferenceCLI$delayedInit$body.apply(InferenceCLI.scala:38)                                                                                                                                                
at scala.Function0.apply$mcV$sp(Function0.scala:39)                                                                                                                                                                    
at scala.Function0.apply$mcV$sp$(Function0.scala:39)                                                                                                                                                                   
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)                                                                                                                                            
at scala.App.$anonfun$main$1$adapted(App.scala:80)                                                                                                                                                                     
at scala.collection.immutable.List.foreach(List.scala:392)                                                                                                                                                             
at scala.App.main(App.scala:80)                                                                                                                                                                                        
at scala.App.main$(App.scala:78)                                                                                                                                                                                       
at lomrf.app.InferenceCLI$.main(InferenceCLI.scala:38)                                                                                                                                                                 
at lomrf.app.LoMRF$.$anonfun$new$1(LoMRF.scala:32)                                                                                                                                                                     
at lomrf.app.LoMRF$.$anonfun$new$1$adapted(LoMRF.scala:32)                                                                                                                                                             
at lomrf.util.opt.MasterOptionParser.parse(MasterOptionParser.scala:49)                                                                                                                                                
at lomrf.util.opt.MasterOptionParser.parse$(MasterOptionParser.scala:37)                                                                                                                                               
at lomrf.app.LoMRF$.parse(LoMRF.scala:25)                                                                                                                                                                              
at lomrf.app.LoMRF$.delayedEndpoint$lomrf$app$LoMRF$1(LoMRF.scala:46)                                                                                                                                                  
at lomrf.app.LoMRF$delayedInit$body.apply(LoMRF.scala:25)                                                                                                                                                              
at scala.Function0.apply$mcV$sp(Function0.scala:39)                                                                                                                                                                    
at scala.Function0.apply$mcV$sp$(Function0.scala:39)                                                                                                                                                                   
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)                                                                                                                                            
at scala.App.$anonfun$main$1$adapted(App.scala:80)                                                                                                                                                                     
at scala.collection.immutable.List.foreach(List.scala:392)                                                                                                                                                             
at scala.App.main(App.scala:80)                                                                                                                                                                                        
at scala.App.main$(App.scala:78)                                                                                                                                                                                       
at lomrf.app.LoMRF$.main(LoMRF.scala:25)                                                                                                                                                                               
at lomrf.app.LoMRF.main(LoMRF.scala) 
```

I am not sure what I am doing wrong. Please advise. Many thanks

**Comment by vagmcs** [comment]
Hello @a-little-srdjan,

Try using Java 8 instead of 11. I believe that may be the problem.

**Comment by a-little-srdjan** [comment]
Unfortunately, that does not seem to help. My JDK version is ```openjdk version "1.8.0_242"```.

sbt test seems ok. I will try and go about it from scala REPL and see if that helps.

**Comment by a-little-srdjan** [comment]
haha. I am an idiot. the bug is at:
```
diff --git a/src/main/scala/lomrf/app/InferenceCLI.scala b/src/main/scala/lomrf/app/InferenceCLI.scala                                                                                                                 index 6bb5060..dad0c02 100644    
                                                                                                                                                                                  --- a/src/main/scala/lomrf/app/InferenceCLI.scala                                                                                                                                                                      

+++ b/src/main/scala/lomrf/app/InferenceCLI.scala                                                                                                                                                                      @@ -324,7 +324,7 @@ object InferenceCLI extends CLIApp {                                                                                                                                                                  
-         |  (targetCost) Target cost: ${_targetCost}                                                                                                                                                                  
+         |  (targetCost) Target cost: ${_targetCost.toString}                                                                                                                                                                   ```

Will issue a PR

**Comment by a-little-srdjan** [comment]
https://github.com/anskarl/LoMRF/pull/20/files

**Comment by anskarl** [comment]
I am closing the issue since PR #20 has been merged to master
